### ISSUE TITLE
Antifraud question

### ISSUE THREAD

**Issue by MrSent** [tipstrade/TipsTrade-HMRC#11]
I had an email from HMRC complaining about antifraud headers. Things are still working but, they complained nonetheless. They say that mine might be wrong. When my application loads it calls a function that loads the client and antifraud. Here is that function:

```c#
        private void LoadClientAndAntiFraud()
        {
            antiFraud = new TipsTrade.HMRC.AntiFraud.AntiFraud()
            {
                ConnectionMethod = TipsTrade.HMRC.AntiFraud.ConnectionMethod.DESKTOP_APP_DIRECT,
                DeviceID = appSettings.AntiFraudDeviceID,
                Screens = new TipsTrade.HMRC.AntiFraud.Screen[] { new TipsTrade.HMRC.AntiFraud.Screen() { ColourDepth = 32, ScalingFactor = 1, Size = new Size(1920, 1080) } },
                TimeZone = TimeZoneInfo.Local,
                VendorVersion = new System.Collections.Generic.Dictionary<string, string>() { { Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyDescriptionAttribute), false).OfType<AssemblyDescriptionAttribute>().FirstOrDefault().Description, Assembly.GetExecutingAssembly().GetName().Version.ToString() } },
                WindowSize = new TipsTrade.HMRC.AntiFraud.Size(1024,768)
            };

            antiFraud.PopulateLocalIPs();
            antiFraud.PopulateMACAddresses();
            //antiFraud.PopulateScreens();
            antiFraud.PopulateUserAgent();

            client.ClientID = sClientId;
            client.ClientSecret = sClientSecret;
            client.ServerToken = sServerToken;
            client.AntiFraud = antiFraud;
        }
```
Where I have appSettings.AntiFraudDeviceID, this pulls a GUID string from a config file. As this application may be installed on multiple machines, do I need the same GUID, or a different one per installation? Also, am I setting the antifraud headers correctly? Do I need the populate functions uncommented?

Thanks

**Comment by MrSent** [comment]
Actually, I don't think I was setting them correctly. I think I do need a new GUID for each installation as a device ID. I am sure I need to call the 3 anti fraud methods for the IPs, MAC addresses, and User Agents. I do not think I need the populate screens function. I think the UserIDs is missing, so the new function is:

```c#
        private void LoadClientAndAntiFraud()
        {
            antiFraud = new TipsTrade.HMRC.AntiFraud.AntiFraud()
            {
                ConnectionMethod = TipsTrade.HMRC.AntiFraud.ConnectionMethod.DESKTOP_APP_DIRECT,
                DeviceID = appSettings.AntiFraudDeviceID,
                Screens = new TipsTrade.HMRC.AntiFraud.Screen[] { new TipsTrade.HMRC.AntiFraud.Screen() { ColourDepth = 32, ScalingFactor = 1, Size = new Size(1920, 1080) } },
                TimeZone = TimeZoneInfo.Local,
                VendorVersion = new System.Collections.Generic.Dictionary<string, string>() { { Assembly.GetExecutingAssembly().GetCustomAttributes(typeof(AssemblyDescriptionAttribute), false).OfType<AssemblyDescriptionAttribute>().FirstOrDefault().Description, Assembly.GetExecutingAssembly().GetName().Version.ToString() } },
                WindowSize = new TipsTrade.HMRC.AntiFraud.Size(1024, 768),
                UserIDs = new Dictionary<string, string>() { { "os", System.Environment.UserName } }
            };

            antiFraud.PopulateLocalIPs();
            antiFraud.PopulateMACAddresses();
            antiFraud.PopulateUserAgent();

            client.ClientID = sClientId;
            client.ClientSecret = sClientSecret;
            client.ServerToken = sServerToken;
            client.AntiFraud = antiFraud;
        }
```

That look right?

**Comment by tipstrade** [comment]
Funnily enough, I had a similar email from HMRC, at which I took umbridge because I was settings the headers correctly, until I realised:
* I hadn't set the `ConnectionMethod` property correctly 🤦‍♂️
* I leaving out some headers that I thought were optional but weren't
* I wasn't using a unique enough DeviceID (I was using the Volume serial), I now use a GUID.

Since then they've stopped sending out the notifications (for obvious reasons), but as far as I'm aware, I'm setting them correctly now. What you have in your 2nd post pretty much matches (see below) what I'm using.

I also added the [Test Fraud Prevention Headers API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/txm-fph-validator-api/1.0) in v.0.0.2.7, which should allow you to verify that the headers you are sending are valid. Have a look at [FraudPreventionTests.cs](https://github.com/tipstrade/TipsTrade-HMRC/blob/master/Tests/FraudPreventionTests.cs). I now run the `Client` through the validate API to ensure I don't push out a release that doesn't send the correct headers.

``` VB.net
#If DEBUG Then
      Dim validated = client.TestFraudPrevention.Validate()
      If validated.Errors.Any() Then
        Throw New Exception()
      End If
#End If

```

However, when writing those tests I found that the service returns an error for some optional arguments. It's possible that the production API does too. If you look at [TestsBase.cs](https://github.com/tipstrade/TipsTrade-HMRC/blob/master/Tests/TestBase.cs), you'll see the tests headers (although they're for a batch process).
``` c#
      // Even though the documentation states that that these are optional, the API returns an error
      client.AntiFraud.UserAgent.DeviceManufacturer = "Dell";
      client.AntiFraud.UserAgent.DeviceModel = "XPS";
```

In our office, all the desktops are identical so it was a simple case of hardcoding the make & model as WMI doesn't return the values for those machines.

**Comment by MrSent** [comment]
I saw the hard coding of the device manufacturer and model and I saw the commented note. I may add these as options in a config file along with the device ID. On first run, I need to generate a GUID and store that as well going forward. I will test my modified code and upgrade the nuget package. I have another query but I'll do some test code first before posting a new issue as I think I can get round it. It's to do with date ranges with getting obligations. Keep up the good work!

**Comment by MrSent** [comment]
In TestBase.cs in the GetClient method you have the MultiFactor code block. I know the test is for the batch process, but MFA is also for desktop app direct.

```c#
      client.AntiFraud.MultiFactor = new[] {
        new MultiFactor() {
          Method = MFAMethod.AUTH_CODE,
          TimeStamp = DateTime.Now,
          UniqueReference = $"{Guid.NewGuid()}"
        }
      };
```
Just a query on that. If I'm using desktop app direct, which I'm happy to use, should I also include MFA in the anti fraud header? Reading the documentation at HMRC here https://developer.service.hmrc.gov.uk/api-documentation/docs/fraud-prevention it says that all headers must be sent for the connection method. So I would assume I need to add the MFA code block for my method. That's fine. Even reading the documentation I wasn't sure about the UniqueReference. I get that it should contain a hashed number if sent via SMS. Your test code sends a new GUID each time. The way I read this is that in production, the unique reference is unlikely to change, so a bit like the device ID in that setting it when the application first runs and using that going forward rather than a new GUID each time.

Would that seem reasonable?

I suppose that begs the question about the vendor licence Ids as well

```c#
   client.AntiFraud.VendorLicenceIDs = new Dictionary<string, string>() {
        { "Example", "https://example.com" }
      };
```
If I didn't populate them with anything, does the API send an empty value or does it omit them entirely? HMRC says empty values should be sent as blank strings.

**Comment by tipstrade** [comment]
I'll be honest, the Multi-Factor thing confused me. I'd assumed that it refered to how the user authenticated with the client, as we have no idea how the user authenticated with HMRC (or do we?) Because of this, I leave it empty for our `DESKTOP_APP_DIRECT` client:

> If only a single factor (for example, username and password) is being used, submit the header with an empty value or omit it entirely.

The same goes with Vendor License IDs:

> If there are no such licenses on the originating device, then submit the header with an empty value or omit it entirely.

The client itself does a basic sanity check to ensure that a property eg. `AntiFraud.DeviceID` is not null or `AntiFraud.LocalIPs ` is not an empty `IEnumerable`, but that's it. The client then generates a header value based on the data provided. If that value is an empty string then it doesn't add the header to the request.

> Only in these cases, you must submit the header with an empty value or omit it entirely. You must not supply null values.
>
> In all other cases, you must submit a valid value and not leave the header empty.

Again, I find some of the requirments somewhat ambiguous. **_"It is mandatory to send all header information for your connection method"_** but if you can't collect them then the header can be submitted with an empty value, or can be omitted entirely. In my mind those are mutually exclusive!

To be honest, the only thing I can advise is to populate them as best you can based on the fraud-prevention documentation (the client can only go so far in validating what you provide), throw them at the Test API, fix errors, rinse-and-repeat.

I'm perfectly happy to modify the client if you can show it's submitting invalid headers or missing values, but I'm afraid the interpretation of what to put into the headers is up to you 😃

You've probably seen it, but there is also a method `AntiFraud.GetAntiFraudHeaders` which might help you as you can see exactly what headers the client will send so you can verify them against what the HMRC docs say.

**Comment by MrSent** [comment]
Thanks for your help. So far, that seems to solve things.
